# Generated by Django 3.0.6 on 2021-12-19 18:04
from django.db import migrations, models
import django.db.models.deletion

from src.apps.cars.models import FuelType


# def change_fueltype_in_cartable(apps, schema_editor):
#     Car = apps.get_model('cars', 'Car')
#     for car in Car.objects.distinct('fueltype'):
#         FuelType.objects.create(name=car.fueltype)
#     for car in Car.objects.all():
#         car.fueltype = FuelType.objects.filter(name=car.fueltype).first().id
#         car.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('gasoline', 'Gasoline')], default='diesel', max_length=20)),
            ],
            options={
                'verbose_name': 'Fuel Type',
                'verbose_name_plural': 'Fuel Types',
            },
        ),
        # migrations.RunPython(change_fueltype_in_cartable),
        migrations.RemoveField(
            model_name='car',
            name='fuel_type',
        ),
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.FuelType'),
        ),
    ]
